In [1]:
print("hello world!")

hello world!


In [2]:
import numpy as np

In [3]:
myArr=np.array([22,43,2,234,44],np.int8)

In [4]:
myArr

array([ 22,  43,   2, -22,  44], dtype=int8)

In [5]:
myArr[2]

2

In [6]:
myArr[1]

43

In [7]:
myArr.shape()

TypeError: 'tuple' object is not callable

In [ ]:
myArr.shape

In [ ]:
myArr.dType

In [ ]:
myArr.dtype

In [ ]:
myArr

In [ ]:
listarray=[[2,3,4],[5,8,5],[1,0,8]]

In [ ]:
listarray.size


In [ ]:
listarray.size

In [ ]:
listarray.shape

In [ ]:
listarray.dtype


In [ ]:
listarray

In [ ]:
listarray.size
listarray.shape

In [ ]:
l1=[[2, 3, 4], [5, 8, 5], [1, 0, 8]]

In [ ]:
l1.shape

In [ ]:
l1=np.array([[2, 3, 4], [5, 8, 5], [1, 0, 8]])

In [8]:
l1.shape

NameError: name 'l1' is not defined

In [15]:
l1

array([[2, 3, 4],
       [5, 8, 5],
       [1, 0, 8]])

In [10]:
l1=np.array([[2, 3, 4], [5, 8, 5], [1, 0, 8]])

In [11]:
l1

array([[2, 3, 4],
       [5, 8, 5],
       [1, 0, 8]])

In [12]:
l1.shape

(3, 3)

In [13]:
l1.size

9

In [14]:
l1.dtype

dtype('int32')

In [16]:
np.array([23,54,767])

array([ 23,  54, 767])

In [17]:
zeros=np.zeros((3,9))

In [18]:
zeros

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [19]:
zeros.dtype

dtype('float64')

In [20]:
zeros.shape

(3, 9)

In [21]:
zeros.size

27

In [22]:
zeros

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [25]:
rng=np.arange(13)

In [26]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [33]:
lspace=np.linspace(1,4,5)

In [34]:
lspace

array([1.  , 1.75, 2.5 , 3.25, 4.  ])

In [35]:
emp=np.empty((4,6))

In [36]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.20160575e-306, 1.86921007e-306, 1.06810132e-306],
       [7.56599807e-307, 8.90104239e-307, 1.24610383e-306,
        1.69118108e-306, 8.06632139e-308, 1.20160711e-306],
       [1.69119330e-306, 2.22522597e-306, 1.02360188e-306,
        6.23059726e-307, 1.02360188e-306, 6.23059726e-307],
       [1.02360188e-306, 8.90094053e-307, 1.60218763e-306,
        1.11261570e-306, 1.42410974e-306, 1.42404727e-306]])

In [37]:
emp_like=np.empty_like(lspace)

In [38]:
emp_like

array([1.  , 1.75, 2.5 , 3.25, 4.  ])

In [39]:
ide=np.identity(45)

In [40]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [41]:
ide.shape

(45, 45)

In [42]:
arr=np.arange(99)

In [43]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [46]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [47]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [48]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [50]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [51]:
arr=arr.reshape(3.33)

TypeError: 'float' object cannot be interpreted as an integer

In [52]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [53]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [54]:
aa=arr.reshape(3,33)

In [55]:
aa

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [57]:
aa=aa.ravel

In [58]:
aa

<function ndarray.ravel>

In [59]:
aa

<function ndarray.ravel>

In [60]:
aa.shape

AttributeError: 'builtin_function_or_method' object has no attribute 'shape'

In [61]:
x=[[2,5,7],[1,0,5],[3,23,3]]

In [62]:
x

[[2, 5, 7], [1, 0, 5], [3, 23, 3]]

In [63]:
ar=np.array(x)

In [64]:
a

NameError: name 'a' is not defined

In [65]:
ar

array([[ 2,  5,  7],
       [ 1,  0,  5],
       [ 3, 23,  3]])

In [66]:
ar.sum(axis=0)

array([ 6, 28, 15])

In [67]:
ar.sum(axis=1)

array([14,  6, 29])

In [68]:
ar.T

array([[ 2,  1,  3],
       [ 5,  0, 23],
       [ 7,  5,  3]])

In [69]:
ar.flat

In [70]:
for item in ar.flat:
    print(item)

2
5
7
1
0
5
3
23
3


In [71]:
ar.ndim

2

In [72]:
ar.size

9

In [74]:
ar.nbytes

36

In [75]:
one=np.array([3,5,7,8,1,12,3454,5445,554,0,1])

In [76]:
one

array([   3,    5,    7,    8,    1,   12, 3454, 5445,  554,    0,    1])

In [77]:
one.argmax()

7

In [78]:
one.argmin()

9

In [79]:
one.argsort()

array([ 9,  4, 10,  0,  1,  2,  3,  5,  8,  6,  7], dtype=int64)

In [80]:

ar.argmin()

4

In [81]:
ar

array([[ 2,  5,  7],
       [ 1,  0,  5],
       [ 3, 23,  3]])

In [82]:
ar.argmax()

7

In [83]:
ar.argsort()

array([[0, 1, 2],
       [1, 0, 2],
       [0, 2, 1]], dtype=int64)

In [84]:
ar.argsort(axis=0)

array([[1, 1, 2],
       [0, 0, 1],
       [2, 2, 0]], dtype=int64)

In [85]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [1, 0, 2],
       [0, 2, 1]], dtype=int64)

In [86]:
ar.ravel

<function ndarray.ravel>

In [87]:
ar.ravel()

array([ 2,  5,  7,  1,  0,  5,  3, 23,  3])

In [88]:
ar.reshape(9,1)

array([[ 2],
       [ 5],
       [ 7],
       [ 1],
       [ 0],
       [ 5],
       [ 3],
       [23],
       [ 3]])

In [89]:
ar.reshape(9,0)

ValueError: cannot reshape array of size 9 into shape (9,0)

In [90]:
a=np.array(ar)

In [91]:
a

array([[ 2,  5,  7],
       [ 1,  0,  5],
       [ 3, 23,  3]])

In [92]:
a+ar

array([[ 4, 10, 14],
       [ 2,  0, 10],
       [ 6, 46,  6]])

In [93]:
ar

array([[ 2,  5,  7],
       [ 1,  0,  5],
       [ 3, 23,  3]])

In [94]:
a*ar

array([[  4,  25,  49],
       [  1,   0,  25],
       [  9, 529,   9]])

In [95]:
np.sqrt(ar)

array([[1.41421356, 2.23606798, 2.64575131],
       [1.        , 0.        , 2.23606798],
       [1.73205081, 4.79583152, 1.73205081]])

In [96]:
ar.sum()

49

In [97]:
ar.min()

0

In [98]:
ar.max()

23

In [99]:
np.where(ar>5)

(array([0, 2], dtype=int64), array([2, 1], dtype=int64))

In [100]:
type(np.where(ar>5))

tuple

In [101]:
np.count_nonzero(ar)

8

In [103]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 2, 0, 1, 2], dtype=int64))

In [104]:
import sys

In [105]:
pyar=[2,0,1,3]

In [106]:
npar=np.array(pyar)

In [108]:
npar

array([2, 0, 1, 3])

In [109]:
sys.getsizeof(1)*len(pyar)

112

In [112]:
npar.size * pyar.itemsize

AttributeError: 'list' object has no attribute 'itemsize'